version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_calls
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://root:root@postgres:5432/test_calls
      - REDIS_URL=redis://redis:6379/0
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./app:/app/app

  worker:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://root:root@postgres:5432/test_calls
      - REDIS_URL=redis://redis:6379/0
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./app:/app/app

volumes:
  postgres_data: